---
- name: copy priv_validator_state
  become: true
  template:
    src: 'validatorState.j2'
    dest: '{{ horcrux_dir }}/.horcrux/state/{{ chain_id }}_priv_validator_state.json'
    owner: '{{ horcrux_user }}'
    group: '{{ horcrux_user }}'
    mode: '0600'

- name: copy share_sign_state
  become: true
  template:
    src: 'validatorState.j2'
    dest: '{{ horcrux_dir }}/.horcrux/state/{{ chain_id }}_share_sign_state.json'
    owner: '{{ horcrux_user }}'
    group: '{{ horcrux_user }}'
    mode: '0600'

- name: restart horcrux service
  become: true
  systemd:
    name: horcrux
    state: restarted
    daemon_reload: true
    enabled: true  