---
- name: Initialize horcrux config (DBG - about to run these commands)
  debug:
    msg: "{{ horcrux_dir }}/go/bin/horcrux config init {{ lookup('template', 'signer_order.j2') }}"

- name: Copy horcrux init script
  template:
    src: 'signer_order.j2'
    dest: '{{ horcrux_dir }}/init_horcrux.sh'
    owner: '{{ horcrux_user }}'
    group: '{{ horcrux_user }}'
    mode: '0700'

- name: Initializing horcrux config actual
  command: sudo su - "{{ horcrux_user }}" -c "{{ horcrux_dir}}/init_horcrux.sh"

- name: Generate private keys
  local_action: command make genkeys
  run_once: True

- name: Copy keys
  copy:
    src: "keys/private_share_{{ signorder }}.json"
    dest: "{{ horcrux_dir }}/.horcrux/share.json"
    owner: "{{ horcrux_user }}"
    group: "{{ horcrux_user }}"
    mode: '0400'