---
- name: Clone horcrux repo
  git:
    repo: '{{ horcrux_repo }}'
    dest: '{{ horcrux_dir }}/horcrux'

- name: Install horcrux
  command: '{{ item }}'
  args:
    chdir: '{{ horcrux_dir }}/horcrux'
  with_items:
    - 'git fetch'
    - 'git checkout {{ horcrux_version }}'
    - 'make install'
  environment:
    PATH: '{{ path }}'
    GOPATH: '{{ horcrux_dir }}/go'

- name: Copy .profile
  template:
    src: 'profile.j2'
    dest: '{{ horcrux_dir }}/.profile'
    owner: '{{ horcrux_user }}'
    group: '{{ horcrux_user }}'
    mode: '0600'
